/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "BEGIN": "开始",
    "Universe": "宇宙",
    "Universe Essence": "宇宙精华",
    "Unlock Quarks": "解锁夸克",
    "Unlock Hadrons": "解锁强子",
    "Unlock Photons": "解锁光子",
    "Unlock Universal Upgrades": "解锁宇宙升级",
    ", and are multiplying Hadron gain by": "，并且将 强子 增益乘以",
    ", but divide Anti-Blue Quark gain by": "，但将 反蓝夸克 增益除以",
    ", but divide Anti-Green Quark gain by": "，但将 反绿夸克 增益除以",
    ", but divide Anti-Red Quark gain by": "，但将 反红夸克 增益除以",
    "Amount:": "数量:",
    "Auto:": "自动:",
    "Cost:": "成本:",
    "Created by": "作者",
    "Currently:": "当前:",
    "Dimensional Depths": "维度深度",
    "Exit the Void.": "退出虚空。",
    "Export Save": "导出存档",
    "Force an Annihilation reset, and reset Photonic Matter & all Photons to gain": "强制湮灭重置，并重置光子物质和所有光子以获得",
    "Hadrons": "强子",
    "Import Save": "导入存档",
    "Level:": "等级:",
    "Annihilate all previous progress to gain": "湮灭所有以前的进度以获得",
    "Annihilation Energy": "湮灭能量",
    "Anti-Blue Quarks, which multiply Blue Quark gain by": "反蓝夸克，将蓝夸克增益乘以",
    "Anti-Green Quarks, which multiply Green Quark gain by": "反绿夸克，将绿夸克增益乘以",
    "Anti-Red Quarks, which multiply Red Quark gain by": "反红夸克，将红夸克增益乘以",
    "Blue Quarks, which multiply Red Quark gain by": "蓝夸克，将红夸克增益乘以",
    "Charge your Quarks.": "给你的夸克充能。",
    "Dimensional Depths, which boost Universe Growth Speed by": "维度深度，将宇宙增长速度提高",
    "In the Void, all Universal Upgrades are disabled, and Annihilation Upgrades are replaced by Void Upgrades.": "在虚空中，所有宇宙升级都被禁用，湮灭升级被虚空升级取代。",
    "Max All": "全部最大",
    "Next at": "下一个在 ",
    "Options": "选项",
    "Reach": "达到",
    "Req:": "要求:",
    "Sell All Wave Accelerators": "出售所有波加速器",
    "Space-Time Fabric": "时空结构",
    "Total Quarks": "总夸克",
    "Ultrawaves.": "超声波。",
    "Universe Essence.": "宇宙精华。",
    "Unlock Antiquarks": "解锁反夸克",
    "Unlock Void": "解锁虚空",
    "Photonic Matter": "光子物质",
    "Reset your Hadrons for a Boost": "重置你的强子以获得提升",
    "Depth": "深度",
    "to delve into Dimensional Depth": "深入研究维度深度",
    "Total Annihilation Energy, which makes the Universe's size boost its growth rate by": "总湮灭能量，这使得宇宙的大小增加了",
    "Void Upgrades can be purchased twice: 1 Purchase = Works in Void, 2 Purchases = Works in & out of Void": "虚空升级可以购买两次：1 次购买 = 在虚空中工作，2 次购买 = 在虚空内外工作",
    "You have completed": "你完成了",
    "Your Anti-Quarks have generated": "你的 反夸克 生成了",
    "Your Space-Time Fabric have generated": "你的 时空结构 生成了",
    "Your universe has a volume of": "你的宇宙体积为",
    "Hadronic Boosters, which are strengthening Quark & Gluon effects by": "强子助推器，增强夸克和胶子效果",
    "Makes Total Universal Upgrade Level add extra Hadronic Boosters.": "使总宇宙升级等级增加额外的强子助推器。",
    "Makes Unspent Annihilation Energy strengthen all Quark effects.": "使未消耗的湮灭能量增强所有夸克效果。",
    "Next at Dimensional Depth": "下一个在维度深度",
    "of Gluon": "胶子",
    "Quark Charge, which strengthens all Quark effects by": "夸克充能，通过以下方式增强所有夸克效应",
    "Red Quarks, which multiply Green Quark gain by": "红夸克，将绿夸克增益乘以",
    "Respec Universal Upgrades": "重洗宇宙升级",
    "Space-Time Fabric is gained based on your Universe's size, but slows down over time since last Dimensional Depth": "时空结构是根据你的宇宙大小获得的，但自上次维度深度以来会随着时间的推移而减慢",
    "Your Space-Time Fabric has generated": "你的 时空结构 生成了",
    "Annihilation Energy.": "湮灭能量。",
    "Improve the Dimensional Depth effect.": "提高维度深度效果。",
    "Green Quarks, which multiply Blue Quark gain by": "绿夸克，将蓝夸克增益乘以",
    "Dimensional Depths lower their goal.": "维度深度降低了他们的目标。",
    "Unlock Quarks to unlock new Universal Upgrades": "解锁夸克以解锁新的宇宙升级",
    "Unlock Universal Upgrades to unlock new Universal Upgrades": "解锁宇宙升级以解锁新的宇宙升级",
    "later.": " 之后。",
    "later": "之后",
    "Credit to Letorin for helping plan this out :)": "感谢Letorin的帮助 :)",
    "Add 10% to the Quark Charge effect.": "增加 10% 的夸克充能效果。",
    "Quarks": "夸克",
    "The Gluon grows 50% faster.": "胶子 的增长速度提高了 50%。",
    "The Gluon is": "胶子有 ",
    "Total Quarks add to Universe Upgrade 2's base.": "总夸克添加到宇宙升级 2 的基数。",
    "Unlock Hadrons to unlock new Universal Upgrades": "解锁强子以解锁新的宇宙升级",
    "long, which boosts Universe Growth Speed by": " 那么长，将宇宙成长速度提升",
    "Reach 4 Hadronic Boosters to unlock new Universal Upgrades": "达到 4 个强子助推器以解锁新的宇宙升级",
    "The Gluon boosts Hadron gain": "胶子提高强子增益",
    "The Gluon's effect is stronger based on your Hadrons.": "胶子的效果基于你的强子而更强。",
    "Universal Compaction starts later.": "宇宙压缩在之后开始。",
    "Annihilation": "湮灭",
    "Photons": "光子",
    "Red Quarks cheapen Quark Charge.": "红夸克让夸克充能更便宜。",
    "You can activate 3 Annihilation Boosts at once.": "您可以一次激活 3 个湮灭助推器。",
    "You get Depths in bulk, and AE & Space-Time Fabric boost each other's gain.": "你可以批量获得深度，AE 和时空结构相互提升。",
    "Upgrades": "升级",
    "Void": "虚空",
    "Universe of Darkness": "黑暗宇宙",
    "Ultrawaves": "超声波",
    "ACTIVE": "激活",
    "INACTIVE": "非激活",
    "Adds 3.45 extra Hadronic Boosters & Void Rebuyable Upgrades": "添加 3.45 个额外的强子助推器和虚空可重买升级",
    "All Universal Upgrades are cheaper based on your Dimensional Depth.": "根据您的维度深度，所有宇宙升级都更便宜。",
    "Antiquarks": "反夸克",
    "Automate Dimensional Depths, and Universal Upgrades do not spend Universe Essence.": "自动化维度深度和宇宙升级不消耗宇宙精华。",
    "Automate Quark Charge & Hadronic Boosts.": "自动化夸克充电和强子加速。",
    "Automate Universal Upgrades, and you can activate 2 Annihilation Boosts at once.": "自动化宇宙升级，您可以一次激活 2 个歼灭助推器。",
    "Base Blue Photon gain:": "基础蓝色光子增益：",
    "Base Green Photon gain:": "基础绿色光子增益：",
    "Base Orange Photon gain:": "基础橙色光子增益：",
    "Base Photon gain is multiplied & raised to an exponent based on Total AE.": "基础光子增益乘以并提高到基于总 AE 的指数。",
    "Base Purple Photon gain:": "基础紫色光子增益：",
    "Base Red Photon gain:": "基础红光子增益：",
    "Base Ultraviolet Photon gain:": "基础紫外光子增益：",
    "Base X-Ray Photon gain:": "基本 X 射线光子增益：",
    "Base Yellow Photon gain:": "基础黄色光子增益：",
    "Boosts": "提升",
    "Bought Hadronic Boosters boost Universe Essence gain.": "购买的强子助推器提高了宇宙精华的增益。",
    "Continuum Error": "连续误差",
    "Double Space-Time Fabric gain.": "双倍时空结构增益。",
    "Effect: Multiply the gain of all Pre-X-Ray Photons by": "效果：将所有 预 X 射线 光子的增益乘以",
    "Effect: Raise the base gain of all Pre-X-Ray Photons ^": "效果：提高所有预 X 射线 光子的基础增益 ^",
    "Effect: Strengthen the effects of all Pre-X-Ray Photons by": "效果：通过以下方式增强所有 预 X 射线 光子的效果",
    "Enter the Void.": "进入虚空。",
    "Hadronic Boosters add to the Hadron effect.": "强子助推器增加了强子效应。",
    "I affects all Universal Upgrades.": "我影响所有宇宙升级。",
    "later)": "之后）",
    "long, which boosts Universe Growth Speed & Quark gain by": "长，将宇宙增长速度和夸克增益提高",
    "Makes Dimensional Depths add extra levels to all Universal Upgrades.": "使维度深度为所有宇宙升级增加额外的级别。",
    "Photonic Matter boosts Space-Time Fabric gain.": "光子物质提高时空结构增益。",
    "Purchase a Blue Photon Generator": "购买蓝色光子发生器",
    "Purchase a Green Photon Generator": "购买绿色光子发生器",
    "Purchase a Orange Photon Generator": "购买橙色光子发生器",
    "Purchase a Purple Photon Generator": "购买紫色光子发生器",
    "Purchase a Red Photon Generator": "购买红色光子发生器",
    "Purchase a Ultraviolet Photon Generator": "购买紫外线光子发生器",
    "Purchase a X-Ray Photon Generator": "购买 X 射线光子发生器",
    "Purchase a Yellow Photon Generator": "购买黄色光子发生器",
    "Quark Charge adds to Universal Upgrade 3's effect.": "夸克充能增加了宇宙升级 3 的效果。",
    "Quark Charge is 150% stronger.": "夸克充能强 150%。",
    "Rebuyable Void Upgrades are 25% stronger.": "可重复购买的虚空升级增强 25%。",
    "Space-Time Fabric boosts its own gain.": "时空结构提升了自身的收益。",
    "Space-Time Fabric reduces the Dimensional Depth requirement.": "时空结构 降低了维度深度要求。",
    "Space-Time Fabric strengthens Annihilation Boosts.": "时空结构加强歼灭助推。",
    "Start with 3 Universal Upgrades unlocked on reset.": "从重置时解锁的 3 个宇宙升级开始。",
    "Start with Quarks, Hadrons, and all Universal Upgrades unlocked.": "从夸克、强子和所有宇宙升级解锁开始。",
    "Strengthens Annihilation Boosts by 495.04%": "强化歼灭提升 495.04%",
    "Temporal Tear": "时间撕裂",
    "The Compressed Gluon is": "压缩胶子是",
    "The Gluon & Hadrons grow 10x as fast.": "胶子和强子的增长速度是原来的 10 倍。",
    "The Gluon boosts Quark gain at a reduced rate.": "胶子以降低的速率提高夸克增益。",
    "The Gluon's effect also affects Quark gain.": "胶子的效果也会影响夸克增益。",
    "The Space-Time Fabric production slowdown is weaker based on AE.": "基于 AE，时空结构 生产放缓较弱。",
    "Triple Annihilation Energy gain.": "三重湮灭能量增益。",
    "Universal Compaction starts 2x later, and Dimensional Depths reset nothing.": "通用压缩在 2 倍后开始，并且维度深度不会重置任何内容。",
    "Universe Essence boosts Space-Time Fabric gain.": "宇宙精华提升时空结构增益。",
    "Unspent AE strengthens Hadronic Boosters.": "未使用的 AE 增强了强子助推器。",
    "Void Upgrades are 25% stronger when bought twice.": "购买两次后，虚空升级增强 25%。",
    "boosts Space-Time Fabric gain.": "提升时空结构增益。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "AE": "AE",
    "Jacorb": "Jacorb",
    "Jacorb's Discord Server": "Jacorb's Discord Server",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Annihilation Boost ": "湮灭提升 ",
    "Wave Accelerator ": "波加速器 ",
    "Universal Slowdown is slowing down your Universe's growth beyond ": "宇宙减速正在减缓你宇宙的增长速度 ",
    "Offline Progress: ": "离线进度: ",
    "Req: ": "要求: ",
    "Universal Compaction is halting your Universe's growth beyond ": "宇宙压缩正在阻止你的宇宙成长",
    "Antiquark Upgrade Power: ": "反夸克升级力量: ",
    "Universal Slowdown starts ": "宇宙减速开始于 ",
    "Green Quarks give free levels to Universe Upgrade ": "绿夸克为宇宙升级提供免费等级 ",
    "Blue Quarks strengthen Universe Upgrade ": "蓝夸克强化宇宙升级 ",
    "Multiplies Photonic Matter production by ": "将 光子物质 产量乘以 ",
    "Multiplies Orange Photon production by ": "将 橙色 光子产量乘以 ",
    "Multiplies Red Photon production by ": "将 红色 光子产量乘以 ",
    "Multiplies Yellow Photon production by ": "将 黄色 光子产量乘以 ",
    "Multiplies Blue Photon production by ": "将 蓝色 光子产量乘以 ",
    "Multiplies Purple Photon production by ": "将 紫色 光子产量乘以",
    "Multiplies Green Photon production by ": "将 绿色 光子产量乘以",
    "Orange Photons: ": "橙色光子: ",
    "Red Photons: ": "红色光子: ",
    "Blue Photons: ": "蓝色光子: ",
    "Purple Photons: ": "紫色光子: ",
    "Green Photons: ": "绿色光子: ",
    "X-Ray Photons: ": "X射线光子: ",
    "Yellow Photons: ": "黄色光子: ",
    "Ultraviolet Photons: ": "紫外线光子: ",
    "Currently: ": "当前: ",
    "Multiplies the production of all previous Photon types by ": "将所有先前光子类型的产量乘以 ",
    "Multiplies the production of UV Photons by ": "将紫外光子的产生乘以 ",
    "Raises AE & Space-Time Fabric's boost to each other's gain ": "提升 AE & 时空结构 对彼此增益的提升 ",
    "Improves the Green Quark effect by ": "提高绿夸克效果 ",
    "Increase Universe Essence gain & Universe Growth Speed by ": "增加宇宙精华增益和宇宙成长速度 ",
    "Increases the AE gain exponent by ": "将 AE 增益指数增加 ",
    "Boost Power: ": "提升功率：",
    "Photonic Matter ": "光子物质",
    "Strengthens Annihilation Boosts by ": "加强湮灭助推器 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "x later": "x 之后",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(×([\d\.]+)\)$/,
    /^\(\+([\d\.]+)\/s\)$/,
    /^\(\+([\d\.]+)e([\d\.,]+)\/s\)$/,
    /^([\d\.]+)e([\d\.,]+)\/s$/,
    /^\(×([\d\.]+)\/s\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^将(.+)$/,
    /^强子(.+)$/,
    /^宇宙(.+)$/,
    /^湮灭(.+)$/,
    /^当前(.+)$/,
    /^光子(.+)$/,
    /^成本(.+)$/,
    /^\{\{(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+) m$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+) \+ ([\d\.]+)$/,
    /^([\d\.,]+)x, \^([\d\.]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)m$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+).$/,
    /^([\d\.]+)e([\d\.,]+)m$/,
    /^([\d\.]+)e([\d\.,]+) m$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^\/([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Hadrons \(\+(.+)\/s\), which are extending the starts of Universal Slowdown & Compaction by$/, '强子（\+$1\/秒），扩展了宇宙减速的起点并压缩了'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Cost: (.+) Ultrawave \(Req (.+) of all other Wave Acc.\)$/, '成本：$1 超声波（要求 $2 所有其他 波加速器.）'],
    [/^(.+)x AE, (.+)x Fabric$/, '$1x AE，$2x 结构'],
    [/^Gain (.+) of Space-Time Fabric gain outside of The Void each second$/, '在虚空之外每秒获得 $1 的时空结构增益'],
    [/^Hadrons' nerf to their own production is (.+) weaker.$/, '强子对自身生产的削弱 $1。'],
    [/^Hadrons' nerf to their own production is (.+) weaker$/, '强子对自己生产的削弱是 $1'],
    [/^Makes Universe Upgrade 2 also make Universal Compaction\'s base start later at (.+) power (.+)$/, '使 宇宙升级 2 也使 宇宙压缩 的基础在 $1 功率 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)\% stronger$/, '$1\% 更强'],
	[/^([\d\.]+)e([\d\.,]+)\% stronger$/, '$1e$2\% 更强'],
	[/^([\d\.]+)\% faster$/, '$1\% 更快'],
	[/^([\d\.]+)e([\d\.,]+)\% faster$/, '$1e$2\% 更快'],
	[/^([\d\.]+)\% weaker$/, '$1\% 更弱'],
	[/^([\d\.]+)e([\d\.,]+)\% weaker$/, '$1e$2\% 更弱'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\-([\d\.]+) depths$/, '\-$1 深度'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);